# Generated by Django 4.0.5 on 2022-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='new_field',
            field=models.IntegerField(default=0),
        ),
    ]
