# Generated by Django 4.0.5 on 2022-10-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='new_field',
        ),
    ]
